Rename-Item -Path "A great example of what Occupied Home Staging can do 👇No new seating. No major purchases.Just d.jpg" -NewName "occupied_home_staging.jpg"
Rename-Item -Path "Clean, calm, and buyer-ready.This bedroom was staged to enhance flow, balance, and visual clarit.jpg" -NewName "clean_calm_bedroom.jpg"
Rename-Item -Path "First impressions aren’t just important… they’re everything. ✨This entryway in a luxury builder  (1).jpg" -NewName "luxury_entryway_2.jpg"
Rename-Item -Path "First impressions aren’t just important… they’re everything. ✨This entryway in a luxury builder .jpg" -NewName "luxury_entryway_1.jpg"
Rename-Item -Path "Swipe to see how we turned this living room from personalized + closed off into bright, inviting.jpg" -NewName "bright_inviting_living.jpg"
Rename-Item -Path "Warm and welcoming. Not just a room - an experience That is the power of staging and this is w.jpg" -NewName "warm_welcoming.jpg"
Rename-Item -Path "When buyers walk into a living room like this, they don’t just see four walls—they see their fut (1).jpg" -NewName "inspiring_living_2.jpg"
Rename-Item -Path "When buyers walk into a living room like this, they don’t just see four walls—they see their fut.jpg" -NewName "inspiring_living_1.jpg"
Rename-Item -Path "✨ Calm. Clean. Minimal. ✨Not every room needs bold colors or heavy styling.Sometimes, staging is.jpg" -NewName "calm_clean_minimal.jpg"
